#!/bin/bash
# Copyright(c) 2016-2100.   jielong.lin.    All rights reserved.
#
#   FileName:     adb_push_SDK.sh
#   Author:       jielong.lin 
#   Email:        jielong.lin@qq.com
#   DateTime:     2019-06-26 17:22:04
#   ModifiedTime: 2019-06-26 17:23:39

JLLPATH="$(which $0)"
JLLPATH="$(dirname ${JLLPATH})"
#source ${JLLPATH}/BashShellLibrary

### Color Echo Usage ###
# Lfn_Sys_ColorEcho ${CvFgRed} ${CvBgWhite} "hello"
# echo -e "hello \033[0m\033[31m\033[43mworld\033[0m"

if [ ! -e SDK ]; then
    echo
    echo "Not found SDK !!!"
    echo
    exit 0
fi


cat >SDK/usr/bin/dumpmem<<EOF
#!/bin/sh

#echo 1 >/proc/sys/vm/drop_caches ; free; free -m
echo 3 >/proc/sys/vm/drop_caches ; free; free -m

EOF
chmod +x SDK/usr/bin/dumpmem

__SDK_FILES=$(cd SDK >/dev/null; \
              find . \( -name 'include' \) -prune -o -type f -print; \
              cd - >/dev/null)

__TGT_SDK_FILES=
OIFS=${IFS}
IFS=$'\n'
for __FL in ${__SDK_FILES}; do
    __FL="${__FL#*./}"
    echo "CHECKing SDK:  ${__FL}"
    __TGT_SDK_FILES="${__TGT_SDK_FILES} ${__FL}"
done
IFS=${OIFS}

adb shell "rm -rvf ${__TGT_SDK_FILES}"
adb shell "sync"

echo
echo
read -p "Continue to UPGRATing SDK if press [y] or not?  YOUR CHOICE: " -n 1 isY
echo

if [ x"${isY}" = x"y" ]; then

OIFS=${IFS}
IFS=$'\n'
for __FL in ${__SDK_FILES}; do
    __S_FL="SDK/${__FL#*./}"
    __D_FL="${__S_FL#*SDK/}"
    __D_FL="/${__D_FL%/*}/"
    if [ -e "$(pwd)/${__S_FL}" -a x"${__D_FL}" != x"//" ]; then
        echo "UPGRATing SDK:  adb push  ${__S_FL}  ${__D_FL}"
        adb push  ${__S_FL}  ${__D_FL}
    else
        echo "UPGRATing SDK:  [FAILURE]  adb push  ${__S_FL}  ${__D_FL}"
    fi
done
IFS=${OIFS}
adb shell "sync"

fi

echo

