
#LOCAL_PATH :=

LOCAL_MODULE :=

LOCAL_SRC_FILES :=

LOCAL_C_INCLUDES :=

LOCAL_SHARED_LIBRARIES :=

LOCAL_STATIC_LIBRARIES :=
# Group static libraries with "-Wl,--start-group" and "-Wl,--end-group" when linking""""

LOCAL_WHOLE_STATIC_LIBRARIES :=

LOCAL_ASFLAGS :=
LOCAL_CFLAGS :=
LOCAL_CPPFLAGS :=
LOCAL_LDFLAGS :=

TARGET_OUT_DIR_LIST :=
TARGET_MODS_LIST :=
TARGET_OBJS_LIST :=
TARGET_OBJS_DIRS_LIST :=


